### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by shijiegu** [LorenFrankLab/non_local_detector#1]
(spyglass) shijiegu@supercell:~$ pip install non_install_detector
ERROR: Could not find a version that satisfies the requirement non_install_detector (from versions: none)
ERROR: No matching distribution found for non_install_detector

(spyglass) shijiegu@supercell:~$ pip3 install non_install_detector
ERROR: Could not find a version that satisfies the requirement non_install_detector (from versions: none)
ERROR: No matching distribution found for non_install_detector

**Comment by edeno** [comment]
You're not using the correct package name: `non_install_detector` -> `non_local_detector`

**Comment by shijiegu** [comment]
oops. Sorry for bothering you.
